Mcs 1243 ramp traversal
NextCenturyCorporation/mcs-ingest pull request #83
Opened 2022-05-03 14:25 UTC by cedorman

Implemented MCS 1243, which keeps track of ramp traversals.  This counts:

- number of times went up
- number of times went down
- number of times started going up and abandoned
- number of times started going down and abandoned
- number of times fell off

2022-05-05 13:54 UTC, ThomasSchellenbergNextCentury commented
@cedorman Were you going to add a description for the new metric in the README?

2022-05-05 14:04 UTC, ThomasSchellenbergNextCentury requested changes
I'm getting a unit test error:

```
======================================================================
ERROR: test_on_ramp (tests.test_scorecard.TestMcsScorecard)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/tschellenberg/Development/darpa/mcs-ingest/tests/test_scorecard.py", line 379, in test_on_ramp
    on_ramp_bool, ramp_id = scorecard.on_ramp(position)
ValueError: too many values to unpack (expected 2)
```

It looks like `on_ramp` returns 3 outputs, but it's only expecting 2 here?

2022-05-05 15:05 UTC, ThomasSchellenbergNextCentury commented on scorecard/scorecard.py
> +                print("")
?

2022-05-05 15:14 UTC, ThomasSchellenbergNextCentury commented on scorecard/scorecard.py
> +        a boolean and, if True, the ID'''
I think this function's return type and docstring need to be updated.

2022-05-05 15:22 UTC, ThomasSchellenbergNextCentury commented on scorecard/scorecard_location_utils.py
> +    #     return is_actually_on or is_near_base
Can you elaborate here?

2022-05-05 15:22 UTC, ThomasSchellenbergNextCentury commented on scorecard/scorecard.py
> +        # when going down ramp....
What are the pros and cons of this?

2022-05-06 13:37 UTC, brianpippin commented on scorecard/scorecard.py
> +        # self.calc_attempt_impossible()
Is this for another ticket where this will be implemented?

2022-05-06 14:35 UTC, cedorman commented on scorecard/scorecard.py
> +        a boolean and, if True, the ID'''
Weird, don't know how it worked on my machine.  Fixed.

2022-05-06 14:35 UTC, cedorman commented on scorecard/scorecard.py
> +                print("")
Dang.  Hate when I leave debugging stuff...

2022-05-06 14:36 UTC, cedorman commented on scorecard/scorecard_location_utils.py
> +    #     return is_actually_on or is_near_base
I improved the comment here, for below comment, and the README.

2022-05-06 14:41 UTC, cedorman commented on scorecard/scorecard.py
> +        # when going down ramp....
Pro:   possibly more accurate counting in edge cases when they do something that we don't catch.  
Con:  really more complicated geometry and logic steps.  

It's a balance between making the logic even more complicated than it already is and having the mathematically 'right'
answer.  I'm convinced that the current logic (it fell!) works in 99% of the cases.  However, I have a sneaking suspicion 
that something could happen where a fall would count or we would miss one.   But I think that doing the geometry / logic
in those cases is not worth time / effort, and I think that I might be adding more logic holes than filling in.

2022-05-06 14:42 UTC, cedorman commented on scorecard/scorecard.py
> +        # self.calc_attempt_impossible()
MCS-860.  Note that this is a catch-all ('it didn't work') and we should be much more explicit about what we want to include.  It would be easy to count all the things that don't count as 'success' if that is what is wanted.

2022-05-06 14:43 UTC, cedorman commented
Updated all the comments, fixed the unit test bug.

2022-05-09 12:08 UTC, ThomasSchellenbergNextCentury approved these changes

2022-05-09 12:56 UTC, brianpippin commented on scorecard/scorecard_location_utils.py
> +def rotate_x_z(x, z, center_x, center_z, rotation):
This function doesn't type the variables like those around it.

2022-05-09 13:24 UTC, cedorman commented on scorecard/scorecard_location_utils.py
> +def rotate_x_z(x, z, center_x, center_z, rotation):
Fixed a couple of functions, to be consistent.

2022-05-09 13:24 UTC, merged